import typing


def collatz(n: int) -> typing.Generator:
    yield n
    while n != 1:
        if n % 2 == 1:
            n = 3 * n + 1
        else:
            n //= 2
        yield n


def main():
    print("Collatz Sequences, generated by class:")
    print("  C8:", [num for num in collatz(8)])
    print("  C9:", [num for num in collatz(9)])
    print("  max(C9):", max(collatz(9)))

    print("Analyzing the return value of a call to collatz:")
    var = collatz(9)
    print("  type:", type(var))
    print("  repr:", var)
    print("  next:", next(var), next(var), "...")
    print("  member functions:", dir(var))


if __name__ == '__main__':
    main()
