import random

HOST = "127.0.0.1"
PORT = 65432

LOGS_WIDTH = 12

LENGTH_MESSAGE_TYPE = 3
LENGTH_SESSION_ID = 16

MSG_REQUEST_SESSION_ID = b"RSI"
MSG_REQUEST_PROCESS_MESSAGE = b'RPM'

MSG_OK = b"OK."
MSG_FAILURE = b"XXX"