@startuml;

hide members

class EnemyFactory {}

together {
    class TrollBuilder {}
    class GhoulBuilder {}
    class WarriorBuilder {}
}

EnemyFactory -down[dotted]-> TrollBuilder   : instantiates
EnemyFactory -down[dotted]-> GhoulBuilder   : " instantiates"
EnemyFactory -down[dotted]-> WarriorBuilder : instantiates

abstract class Enemy
'together {
    class Troll   {}
    class Ghoul   {}
    class Warrior {}
'}

Troll   -up-> Enemy
Ghoul   -up-> Enemy
Warrior -up-> Enemy

class EnemyCoordinator {}

Troll   o.down. EnemyCoordinator
Ghoul   o.down. EnemyCoordinator
Warrior o.down. EnemyCoordinator

TrollBuilder   -[dotted]-> Troll   : " builds"
GhoulBuilder   -[dotted]-> Ghoul   : " builds"
WarriorBuilder -[dotted]-> Warrior : " builds"

abstract class Weapon {}
class Sword
class Club

Bow   -down-> Weapon
Sword -down-> Weapon
Club  -down-> Weapon


Troll             *-- Club
Warrior    "\n          0..1" *-- Sword
Warrior "   0..1" *-- Bow

@enduml;
